### ISSUE TITLE
macOS arm64 build?

### ISSUE THREAD

**Issue by atztogo** [conda-forge/phono3py-feedstock#35]
### Comment:

Is it possible to build osx_arm64?

**Comment by jan-janssen** [comment]
Usually they are opened by the bot automatically once all dependencies are available, just like this one for the phonopy package https://github.com/conda-forge/phonopy-feedstock/pull/96

**Comment by atztogo** [comment]
Thanks @jan-janssen for your quick answer. Does the dependency mean those written in [meta.yaml](https://github.com/conda-forge/phono3py-feedstock/blob/main/recipe/meta.yaml)?

**Comment by jan-janssen** [comment]
I just noticed that we still have to trigger them manually, so I opened the corresponding pull request https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3376

**Comment by jan-janssen** [comment]
For more details https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds

**Comment by atztogo** [comment]
Thanks @jan-janssen. It is starting #36.
